### ISSUE TITLE
Multi-domain binding feature

### ISSUE THREAD

**Issue by ghost** [thkukuk/ypbind-mt#6]
Hi,
Can you please provide documentation on how the multidomain binding feature works? Does it mean what I think it does? that we can bind to 

```
nis.domain-1
nis.domain-2
...
```

at the same time?

Thanks

**Comment by thkukuk** [comment]
Please define `we`.
ypbind can provide the name of the NIS master for several different domains. 
How it works is simple: the client library/application sends a NIS domainname to ypbind and get's back the NIS master for this domain, look at the ypbind protocol.

If your question is, how you can configure your client library/application to use multiple domains: I don't know. This depends on your software and you need to look at that documentation, this has nothing to do with ypbind. E.g. glibc is using yp_get_default_domain() to get the NIS domainname and thus can only support one NIS domain.
